name: Build Windows ARM64

on:
  workflow_dispatch:

env:
  FLUTTER_VERSION: "3.35.6"

jobs:
  build_windows_zip_arm64:
    runs-on: windows-11-arm

    steps:
      - name: Fix long file paths
        run: git config --system core.longpaths true

      - name: Checkout repository
        uses: actions/checkout@v6

      # Install LLVM mingw for ARM64
      - name: Install llvm-mingw-ucrt-aarch64
        run: |
          $ver = "20251202"
          $url = "https://github.com/mstorsjo/llvm-mingw/releases/download/$ver/llvm-mingw-$ver-ucrt-aarch64.zip"
          $zip = "$env:RUNNER_TEMP\llvm.zip"
          $extract = "$env:RUNNER_TEMP\extract"
          $target = "C:\clangarm64"

          curl -L $url -o $zip
          Remove-Item -Path $extract,$target -Recurse -Force -ErrorAction SilentlyContinue
          New-Item -Path $extract -ItemType Directory

          tar -xf $zip -C $extract
          $extractedDir = Get-ChildItem -Path $extract | Select-Object -First 1
          Move-Item -Path $extractedDir.FullName -Destination $target

          $b = "$target\bin"
          "CC=$b\clang.exe" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8
          "CXX=$b\clang++.exe" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8
          "CLANGARM64_BIN=$b" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8
          "CGO_ENABLED=1" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8
          "CLANGARM64_ROOT=$target" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8
          $env:PATH = "$b;$env:PATH"

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: "stable"

      - name: Dependencies
        working-directory: app
        run: flutter pub get

      - name: Compile for Windows ARM64
        working-directory: app
        run: flutter build windows --target-platform=windows-arm64

      - name: Create empty settings.json
        working-directory: app
        run: echo {} > build/windows/arm64/runner/Release/settings.json

      - name: Add DLL files for ARM64
        working-directory: app
        run: |
          $mingw = "$env:CLANGARM64_ROOT\aarch64-w64-mingw32\bin"
          $release = "build\windows\arm64\runner\Release"
          $system = "C:\Windows\System32"

          # Copy mingw DLLs
          Copy-Item "$mingw\libc++.dll" $release
          Copy-Item "$mingw\libunwind.dll" $release
          Copy-Item "$mingw\libwinpthread-1.dll" $release

          # Copy system DLLs
          Copy-Item "$system\msvcp140.dll" $release
          Copy-Item "$system\vcruntime140.dll" $release
          Copy-Item "$system\vcruntime140_1.dll" $release

      - name: Zip compiled files
        working-directory: app
        run: Compress-Archive -Path build/windows/arm64/runner/Release/* -DestinationPath LocalSend.zip

      - name: Upload zip
        uses: actions/upload-artifact@v6
        with:
          name: LocalSend-windows-arm64
          path: app/LocalSend.zip